### ISSUE TITLE
Add an action of like/dislike a product

### ISSUE THREAD

**Issue by infinite147** [CSCI-GA-2820-FA22-003/products#27]
**As a** User 
 **I need** to be able to like/dislike a product, as well as get the count of like/dislike when I need it
 **So that** all customers can make better decisions when they need to buy something
   
 ### Details and Assumptions

- The action of liking a product will be : `PUT /products/id/like`
- The action of disliking a product will be :  `DELETE /products/id/like`
- Users can get the count of likes via: `GET /products/id/like`

 ### Acceptance Criteria  
   
 ```gherkin
 Given A running service
 When An action of like/dislike is made
 Then the according attribute of like/dislike would change accordingly
 ```

 ```gherkin
 Given A running service
 When An query of the count of likes is made
 Then the according attribute of likes would be present to the users
 ```

**Comment by esmuellert** [comment]
Could be more specific. For example, like will be similar to  `PUT /products/id/like`, and dislike will be something similar to `DELETE /products/id/like`

**Comment by esmuellert** [comment]
#28 is the dependency of this issue. It must be done before start with this.
