### ISSUE TITLE
List UI

### ISSUE THREAD

**Issue by hni2236** [CSCI-GA-2820-FA22-003/products#55]
**As a** product manager  
 **I need** to list records 
 **So that** product records can be queried from the database  
   
 ### Details and Assumptions
 * Create a UI page to list product records
 * Run integration tests against UI
   
 ### Acceptance Criteria  
   
 ```gherkin
Given the product system
When product record are queried using UI
Then product system should list product records from the database and print the record.
 ```

**Comment by tzlys** [comment]
I revised the "Query" into "List". And revised the previous "List" UI into "List All" correspondly.
